[2022-08-20 11:24:42] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 11:24:42] [INFO    ] discord.client: logging in using static token
[2022-08-20 11:24:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: df2fbaaf2964e2bad2ff2eb167bd4fb5).
[2022-08-20 11:43:28] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 11:43:28] [INFO    ] discord.client: logging in using static token
[2022-08-20 11:43:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e8a3cf8a388f86a5c0276b5ca49a9032).
[2022-08-20 11:43:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 11:43:49] [INFO    ] discord.client: logging in using static token
[2022-08-20 11:43:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 53e30aa516b33bd7f09d93cebd9cdaac).
[2022-08-20 11:55:54] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 11:55:54] [INFO    ] discord.client: logging in using static token
[2022-08-20 11:55:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1b0b78949770d1aee3ac9b7118ee6e01).
[2022-08-20 12:04:52] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:04:52] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:04:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fe75b0d0be036b6db868c7c71aa4998d).
[2022-08-20 12:25:29] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:25:29] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:25:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3675640df3a083a9004adc1622e4c615).
[2022-08-20 12:25:52] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "koofOt" is not found
[2022-08-20 12:26:26] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "koofiOt?koofiOt" is not found
[2022-08-20 12:28:06] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:28:06] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:28:06] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d4eba216b6c0b30c6a62590cd5c73f9).
[2022-08-20 12:33:32] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:33:32] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:33:32] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:33:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 941b0acfb6ea7b43e93489821ea7fd3d).
[2022-08-20 12:34:13] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:34:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:34:13] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:34:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ab669dbd8b99848dd19b76f20950c8e1).
[2022-08-20 12:34:20] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "asd" is not found
[2022-08-20 12:34:47] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:34:47] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:34:47] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:34:47] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3f3c0db34e287dadc731dce23fdd969a).
[2022-08-20 12:34:52] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "asd" is not found
[2022-08-20 12:36:20] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:36:20] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:36:20] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:36:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0c6177ee827389c87977a0afbfbe070f).
[2022-08-20 12:36:25] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "Ad" is not found
[2022-08-20 12:36:49] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:36:49] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:36:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:36:49] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:36:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3dc5f2108b5814fc68f01c883a9aaf3e).
[2022-08-20 12:37:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:37:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:37:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:37:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:37:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1bd42e22abaf7b12b57161b40420f2b2).
[2022-08-20 12:37:37] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:37:37] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:37:37] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:37:37] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:37:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 10f53287636211da0f40b13c5887e51a).
[2022-08-20 12:37:38] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 231, in on_command_error
    print(ctx.content)
AttributeError: 'Context' object has no attribute 'content'
[2022-08-20 12:37:54] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:37:54] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:37:54] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:37:54] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:37:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cedaabf8a79d7357f73546eb1378ba76).
[2022-08-20 12:37:57] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 231, in on_command_error
    print(ctx.content.message)
AttributeError: 'Context' object has no attribute 'content'
[2022-08-20 12:38:06] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:38:06] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:38:06] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:38:06] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:38:06] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f210080e4f88ae85b588de118a05273d).
[2022-08-20 12:40:19] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:40:19] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:40:19] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:40:19] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:40:19] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d5dd8a523f4c70c9efc7d2e0e38f6bb1).
[2022-08-20 12:40:23] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 231, in on_command_error
    await ctx.message.send(ctx.message)
AttributeError: 'Message' object has no attribute 'send'
[2022-08-20 12:40:34] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:40:34] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:40:34] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:40:34] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:40:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9877a05919076c8771dda0fbaa02c17a).
[2022-08-20 12:42:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:42:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:42:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:42:04] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:42:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b2fdf076ab3ee16b2d3b67f2aea18b7b).
[2022-08-20 12:42:07] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 231, in on_command_error
    await ctx.channel.send(ctx.command)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/abc.py", line 1539, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
[2022-08-20 12:42:39] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:42:39] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:42:39] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:42:39] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:42:41] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:42:41] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:42:41] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:42:41] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:42:44] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2022-08-20 12:42:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bd66ab2c00027472fb2175012e226421).
[2022-08-20 12:43:22] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 12:43:22] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 12:43:22] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 12:43:22] [INFO    ] discord.client: logging in using static token
[2022-08-20 12:43:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 56a5ad4f32041f4a87b4b1e1d4cd4bfe).
[2022-08-20 12:43:26] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
TypeError: on_command_error() missing 1 required positional argument: 'error'
[2022-08-20 13:16:09] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:16:09] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:16:09] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:16:09] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:16:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e3aad625254a63ff0a0a27045cc04f9a).
[2022-08-20 13:17:21] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:17:21] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:17:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:17:21] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:17:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 40ddab3d57d6d7d99a8509e1f382df46).
[2022-08-20 13:19:08] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:19:08] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:19:08] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:19:08] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:19:09] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bf3f71559d2ce8cedf29aa1b2cab5886).
[2022-08-20 13:19:15] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 257, in koofiOt
    embed2.add_field("test1", "sdff")
TypeError: add_field() takes 1 positional argument but 3 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 232, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: add_field() takes 1 positional argument but 3 were given
[2022-08-20 13:19:48] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:19:48] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:19:48] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:19:48] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:19:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6ec38de2ead210126fcd6143f8c1b01b).
[2022-08-20 13:21:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:21:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:21:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:21:40] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:21:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 919c4716bb689d253c4c74bf2f92735c).
[2022-08-20 13:22:13] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:22:13] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:22:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:22:13] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:22:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c6d518eae16c5038646debfcf9b15a75).
[2022-08-20 13:27:45] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:27:45] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:27:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:27:45] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:27:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 98224d59bd942b0049e3c4cb18997f14).
[2022-08-20 13:27:55] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 249, in koofi
    embed = discord.Embed(title="Koofi", colour="Green")
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/embeds.py", line 179, in __init__
    self.colour = colour if colour is not None else color
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/embeds.py", line 323, in colour
    raise TypeError(f'Expected discord.Colour, int, or None but received {value.__class__.__name__} instead.')
TypeError: Expected discord.Colour, int, or None but received str instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 232, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Expected discord.Colour, int, or None but received str instead.
[2022-08-20 13:29:00] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:29:00] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:29:00] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:29:00] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:29:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b532b275e635bf100249cfef63625871).
[2022-08-20 13:29:06] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 249, in koofi
    embed = discord.Embed(title="Koofi", colour=Colour.Green)
NameError: name 'Colour' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 232, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'Colour' is not defined
[2022-08-20 13:30:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:30:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:30:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:30:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:30:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 59ad1da7f28b2558deb3ee95cf2d4c8e).
[2022-08-20 13:30:52] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:30:52] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:30:52] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:30:52] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:30:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 57cf7abc02a2058a5058810e1666e1f5).
[2022-08-20 13:36:25] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:36:25] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:36:25] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:36:25] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:36:25] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 567d53da7873f12ec5ef976044afcd10).
[2022-08-20 13:39:10] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:39:10] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:39:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:39:10] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:39:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 38f90e9a8d0c0232dbfd410612acd29b).
[2022-08-20 13:39:22] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed.set_thumbnail(koofi.jpg)
AttributeError: 'ServiceData' object has no attribute 'jpg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ServiceData' object has no attribute 'jpg'
[2022-08-20 13:39:38] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:39:38] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:39:38] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:39:38] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:39:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 25cb9b940becf85fc374fc16d6681d07).
[2022-08-20 13:39:43] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed.set_thumbnail("koofi.jpg")
TypeError: set_thumbnail() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: set_thumbnail() takes 1 positional argument but 2 were given
[2022-08-20 13:40:39] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:40:39] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:40:39] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:40:39] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:40:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 742fba2ea6516c33ffcb10c302f9670d).
[2022-08-20 13:40:46] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed.set_thumbnail("https://cornwall-plus.co.uk/blog/attractions/koofi/")
TypeError: set_thumbnail() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: set_thumbnail() takes 1 positional argument but 2 were given
[2022-08-20 13:41:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:41:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:41:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:41:40] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:41:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 89c3d914268db80356edd57dc270be6d).
[2022-08-20 13:41:44] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed.set_image("https://cornwall-plus.co.uk/blog/attractions/koofi/")
TypeError: set_image() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: set_image() takes 1 positional argument but 2 were given
[2022-08-20 13:42:51] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:42:51] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:42:51] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:42:51] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:42:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6ec8ec8132912d72db85f9806b18cbb5).
[2022-08-20 13:42:57] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 253, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, datetime = True)
TypeError: __init__() got an unexpected keyword argument 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'datetime'
[2022-08-20 13:43:56] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:43:56] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:43:56] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:43:56] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:43:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cb20346304b57731d94307c6ff149dd7).
[2022-08-20 13:44:14] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, datetime = True)
TypeError: __init__() got an unexpected keyword argument 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'datetime'
[2022-08-20 13:45:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:45:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:45:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:45:02] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:45:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 42df7c72ecd6da08473077a721dd91fe).
[2022-08-20 13:45:07] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp= True)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/embeds.py", line 195, in __init__
    self.timestamp = timestamp
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/embeds.py", line 340, in timestamp
    raise TypeError(f"Expected datetime.datetime or None received {value.__class__.__name__} instead")
TypeError: Expected datetime.datetime or None received bool instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Expected datetime.datetime or None received bool instead
[2022-08-20 13:45:45] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:45:45] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:45:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:45:45] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:45:46] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0a7e8ef9221d358ea88f59343586bcc9).
[2022-08-20 13:45:52] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp= datetime.datetime)
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:46:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:46:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:46:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:46:02] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:46:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 34664a4be7668bc67be70fbe271dc25e).
[2022-08-20 13:46:08] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp= datetime.datetime())
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:46:28] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:46:28] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:46:28] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:46:28] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:46:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 53183b810cff2779706b7b6fb4fb118d).
[2022-08-20 13:46:34] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp= date.now())
AttributeError: type object 'datetime.date' has no attribute 'now'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: type object 'datetime.date' has no attribute 'now'
[2022-08-20 13:47:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:47:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:47:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:47:59] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:47:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8180379d1ad38f974c223b81081cf98c).
[2022-08-20 13:48:58] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:48:58] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:48:58] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:48:58] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:48:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6812080650ad0337412065463be982bd).
[2022-08-20 13:49:03] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=datetime.datetime)
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:49:11] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:49:11] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:49:11] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:49:11] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:49:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f497fe84b0e9e08163d930cc503b6d82).
[2022-08-20 13:49:16] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=datetime.datetime)
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:49:45] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:49:45] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:49:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:49:45] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:49:46] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4149e97df92c006e057c62eeb646fc0a).
[2022-08-20 13:49:54] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=data.datetime.now())
AttributeError: module 'data' has no attribute 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'data' has no attribute 'datetime'
[2022-08-20 13:50:26] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:50:26] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:50:26] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:50:26] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:50:26] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 667528828c380b26f04a71df2de485ce).
[2022-08-20 13:50:32] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=data.datetime)
AttributeError: module 'data' has no attribute 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'data' has no attribute 'datetime'
[2022-08-20 13:50:52] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:50:52] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:50:52] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:50:52] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:50:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 18913df20b18ef4d4b93e13a944e942c).
[2022-08-20 13:50:57] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=data.datetime.datetime)
AttributeError: module 'data' has no attribute 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'data' has no attribute 'datetime'
[2022-08-20 13:51:01] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:51:01] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:51:01] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:51:01] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:51:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0c0541ac78bc4969d800124f95de849f).
[2022-08-20 13:51:06] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=data.datetime.datetime())
AttributeError: module 'data' has no attribute 'datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'data' has no attribute 'datetime'
[2022-08-20 13:52:17] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:52:17] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:52:17] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:52:17] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:52:17] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fd81c13f564ead48fcd4eb59673b2518).
[2022-08-20 13:52:22] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=datetime.datetime.utcnow())
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:53:00] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:53:00] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:53:00] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:53:00] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:53:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d7ea1f337d55d8e919196185aec4d4f).
[2022-08-20 13:53:17] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=datetime.datetime.utcnow())
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:53:35] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:53:35] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:53:35] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:53:35] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:53:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5668c8a9b5cbe584efccf5964faa94aa).
[2022-08-20 13:53:40] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 254, in koofi
    embed = discord.Embed(title="Koofi", description=koofi.FormatOpenMsg(), colour=GREEN, timestamp=datetime.utcnow())
NameError: name 'datetime' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'datetime' is not defined
[2022-08-20 13:54:15] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:54:15] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:54:15] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:54:15] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:54:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dfa30b8769fe7fd2f0a9ef9d235e7839).
[2022-08-20 13:56:56] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:56:56] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:56:56] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:56:56] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:56:56] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 60405b5df05574190550e50a2562e23c).
[2022-08-20 13:57:49] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 13:57:49] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 13:57:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 13:57:49] [INFO    ] discord.client: logging in using static token
[2022-08-20 13:57:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 05eaac326e76ff4a9380f9cd62f80cfa).
[2022-08-20 14:00:53] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:00:53] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:00:53] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:00:53] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:00:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e11802b8499cb27f1a0c93ebd03e950d).
[2022-08-20 14:01:34] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:01:34] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:01:34] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:01:34] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:01:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a42b00323dffd424c898ebdea136a2a4).
[2022-08-20 14:02:07] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 280, in amataOt
    await amata.SetopeningTimeData()
AttributeError: 'ServiceData' object has no attribute 'SetopeningTimeData'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 237, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ServiceData' object has no attribute 'SetopeningTimeData'
[2022-08-20 14:02:56] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:02:56] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:02:56] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:02:56] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:02:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b3c8ead96e1a79ed7cbb1580c5e7aee6).
[2022-08-20 14:05:00] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:05:00] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:05:00] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:05:00] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:05:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e54fa39f02e0a1b971fc4bb1b19ae24e).
[2022-08-20 14:07:14] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:07:14] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:07:14] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:07:14] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:07:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 86eb0f38307f7a65599a5bcb4873f0f2).
[2022-08-20 14:14:15] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:14:15] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:14:15] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:14:15] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:14:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3790aae09c8bcc7b0133d0252bbd0802).
[2022-08-20 14:14:23] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 267, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 245, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:15:35] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:15:35] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:15:35] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:15:35] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:15:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 39166d979b332bbfba09df68da40ed77).
[2022-08-20 14:15:44] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 268, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 246, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:17:13] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:17:13] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:17:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:17:13] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:17:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1b32b348e0d19cf5827fa6ff7e808bcd).
[2022-08-20 14:17:21] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 263, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 241, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:18:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:18:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:18:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:18:04] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:18:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2c38b1393a778c66b8d44212e0e3e029).
[2022-08-20 14:18:14] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 263, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name="koofi" + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 241, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:18:46] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:18:46] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:18:46] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:18:46] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:18:47] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c0081f295e0defd65431772dc15d8b5a).
[2022-08-20 14:18:52] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 265, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 243, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:20:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:20:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:20:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:20:40] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:20:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6e3fb66b37f5e81232e8d6ef65e4cad6).
[2022-08-20 14:20:51] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 268, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name + " Opening Times are:\n")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 246, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:21:36] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:21:36] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:21:36] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:21:36] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:21:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 53188eade116ab6336a17e2cbedb4db5).
[2022-08-20 14:21:42] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 268, in koofiOt
    await koofi.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 150, in ShowOpeningTimes
    embed = discord.Embed(name=self.name, description="Opening Times Are")
TypeError: __init__() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 246, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'name'
[2022-08-20 14:22:31] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:22:31] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:22:31] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:22:31] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:22:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dcab1c612d711164afec42488fbf964a).
[2022-08-20 14:23:54] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:23:54] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:23:54] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:23:54] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:23:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4e13cc8aae747540e96fedc74fd1958e).
[2022-08-20 14:29:53] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:29:53] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:29:53] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:29:53] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:29:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 743ba6b59ad8660f2cdb6b38fa50df49).
[2022-08-20 14:33:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:33:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:33:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:33:04] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:33:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9f83b2255ded29ad94df12a08e04f66f).
[2022-08-20 14:36:33] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:36:33] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:36:33] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:36:33] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:36:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 37cb5a87b5596f541274ba6b857db040).
[2022-08-20 14:37:03] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:37:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:37:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:37:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:37:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a1893b236eadb984c12a248f61f328f2).
[2022-08-20 14:43:44] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:43:44] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:43:44] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:43:44] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:43:46] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:43:46] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:43:46] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:43:46] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:43:47] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 18031debad6881f63dbf6d4714e99bde).
[2022-08-20 14:45:03] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:45:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:45:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:45:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:45:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d8173bd5b3cf3a99d7ce474bd94d0043).
[2022-08-20 14:47:07] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:47:07] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:47:07] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:47:07] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:47:08] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bb06d3eda39e7ba69ccf69408909853b).
[2022-08-20 14:47:47] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[2022-08-20 14:47:47] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:47:47] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:47:47] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:47:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ab8ce060d4d1a841dfb6170ef75c31e3).
[2022-08-20 14:48:30] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:48:30] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:48:30] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:48:30] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:48:31] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0cb83d1a3921145ea41f51c546e382b5).
[2022-08-20 14:49:26] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:49:26] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:49:26] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:49:26] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:49:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d8e6859de9e1536f0060e689705e01d5).
[2022-08-20 14:56:06] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:56:06] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:56:06] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:56:06] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:56:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3fa7cc95195bc28680b2f04a5bbc891f).
[2022-08-20 14:57:13] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:57:13] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:57:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:57:13] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:57:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e3608033fe70589dfa7070124ce25a8b).
[2022-08-20 14:59:46] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 14:59:46] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 14:59:46] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 14:59:46] [INFO    ] discord.client: logging in using static token
[2022-08-20 14:59:46] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2c318d8b07bf3e39de0be30aadbf7e7a).
[2022-08-20 15:00:31] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:00:31] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:00:31] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:00:31] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:00:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e5026862bedcb05a0b9df6ca3a5bb6f6).
[2022-08-20 15:00:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:00:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:00:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:00:59] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:00:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ba4f3da894c0a365cb0843d5542bd86c).
[2022-08-20 15:02:35] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:02:35] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:02:35] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:02:35] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:02:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cffa286ff2208c828ef6fdd79cc2b136).
[2022-08-20 15:10:09] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:10:09] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:10:09] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:10:09] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:10:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c274173388340ebf16a749df59301e09).
[2022-08-20 15:12:50] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:12:50] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:12:50] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:12:50] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:12:51] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 12eee4af3d064bb1b0d4651cbc279a2e).
[2022-08-20 15:12:54] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 235, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 978, in invoke
    await self.prepare(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 895, in prepare
    await self._parse_arguments(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 802, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 654, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: arg is a required argument that is missing.
[2022-08-20 15:13:06] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 235, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 978, in invoke
    await self.prepare(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 895, in prepare
    await self._parse_arguments(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 802, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 654, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: arg is a required argument that is missing.
[2022-08-20 15:14:07] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:14:07] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:14:07] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:14:07] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:14:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9ed0960cbc396bd9163a445ba16a6774).
[2022-08-20 15:14:11] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 249, in ot
    arg = arg.lower()
AttributeError: 'tuple' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 235, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'tuple' object has no attribute 'lower'
[2022-08-20 15:14:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:14:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:14:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:14:40] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:14:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 934ef9ace9ce6da636d18886320668a7).
[2022-08-20 15:14:44] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 249, in ot
    arg[0] = arg[0].lower()
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 235, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: tuple index out of range
[2022-08-20 15:23:44] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:23:44] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:23:44] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:23:44] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:23:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cd12dc477715330a83e48d9ce3456490).
[2022-08-20 15:23:47] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 978, in invoke
    await self.prepare(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 895, in prepare
    await self._parse_arguments(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 802, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 654, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: arg is a required argument that is missing.
[2022-08-20 15:23:50] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:23:56] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:24:04] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:29:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:29:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:29:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:29:04] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:29:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a57df250c4c1705094b7a96a54b2f866).
[2022-08-20 15:29:09] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:29:24] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:29:58] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:29:58] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:29:58] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:29:58] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:29:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 631ad7533dee8be08abe044fc207db30).
[2022-08-20 15:31:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:31:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:31:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:31:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:31:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 73d0107aecf82efd5b64f86e19a14127).
[2022-08-20 15:31:08] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 269, in ot
    embed.add_field(title="", value="Such as: stannarybar or \n FalmouthArtShop")
TypeError: add_field() got an unexpected keyword argument 'title'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: add_field() got an unexpected keyword argument 'title'
[2022-08-20 15:31:22] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:31:22] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:31:22] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:31:22] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:31:23] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 678044545d09f4de0b95ae54619f2ea2).
[2022-08-20 15:31:26] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 269, in ot
    embed.add_field(value="Such as: stannarybar or \n FalmouthArtShop")
TypeError: add_field() missing 1 required keyword-only argument: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: add_field() missing 1 required keyword-only argument: 'name'
[2022-08-20 15:31:37] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:31:37] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:31:37] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:31:37] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:31:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 503f132301134341491d447c9c84252b).
[2022-08-20 15:31:40] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 270, in ot
    await ctx.channel.send(embed=embed)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/abc.py", line 1539, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.name: This field is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.name: This field is required
[2022-08-20 15:31:56] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:31:56] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:31:56] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:31:56] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:31:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 148728f25891b973f067428f886b9b92).
[2022-08-20 15:32:00] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 270, in ot
    await ctx.channel.send(content=None, embed=embed)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/abc.py", line 1539, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.name: This field is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.name: This field is required
[2022-08-20 15:32:23] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:32:23] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:32:23] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:32:23] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:32:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 167651fe654143e4bd70b1a9a824a5a6).
[2022-08-20 15:33:24] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:33:24] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:33:24] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:33:24] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:33:25] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7603482442a878e552cc5ff76f852ca5).
[2022-08-20 15:33:34] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 978, in invoke
    await self.prepare(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 895, in prepare
    await self._parse_arguments(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 802, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 654, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: arg is a required argument that is missing.
[2022-08-20 15:34:02] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 266, in ot
    await ctx.invoke(client.get_command("falmnouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 234, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not callable
[2022-08-20 15:35:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:35:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:35:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:35:02] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:35:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e7f7c0d0d75800aa9b35df3779d628cc).
[2022-08-20 15:43:20] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:43:20] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:43:20] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:43:20] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:43:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 98986d139f2548b52e992b1ce501e9c7).
[2022-08-20 15:43:30] [ERROR   ] discord.client: Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 271, in ot
    await ctx.invoke(client.get_command("falmouthShopOt"))
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 335, in invoke
    return await command(self, *args, **kwargs)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 547, in __call__
    return await self.callback(context, *args, **kwargs)  # type: ignore
  File "main.py", line 397, in falmouthShopOt
    await falmouthShop.SetOpeningTimeData()
  File "main.py", line 67, in SetOpeningTimeData
    self.openingTimesFormatted = await self.ShowOpeningTimes()
  File "main.py", line 155, in ShowOpeningTimes
    if self.openingTimes[i+3] not in foundWeekDays:
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 239, in on_command_error
    raise error
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/FalTracker/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range
[2022-08-20 15:44:17] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:44:17] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:44:17] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:44:17] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:44:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 954f2f946d678a90165e155740da7646).
[2022-08-20 15:47:25] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:47:25] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:47:25] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:47:25] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:47:26] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: de7b107f73b9b077ed1fc08968d07c6e).
[2022-08-20 15:50:20] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:50:20] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:50:26] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:50:26] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:50:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:50:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:51:21] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 15:51:21] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 15:51:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 15:51:21] [INFO    ] discord.client: logging in using static token
[2022-08-20 15:51:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b6aa7be7b04d68a013aaba699b0ca293).
[2022-08-20 16:01:21] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:01:21] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:01:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:01:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:01:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:01:40] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:01:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c3d15b6e2590111895125995bc4c9440).
[2022-08-20 16:03:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:03:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:03:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:03:03] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:03:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 667cef42147a592fbd75077417e57711).
[2022-08-20 16:05:20] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:05:20] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:05:44] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:05:44] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:05:44] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:05:44] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:05:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 86bdef5fd563568ca663ec373a8fc3a4).
[2022-08-20 16:06:16] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:06:16] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:06:16] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:06:16] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:06:17] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 77c53b37e7ae57f3a1294bef17cf0fe0).
[2022-08-20 16:06:42] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:06:42] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:06:42] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:06:42] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:06:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6b08653a933346a3a98cff5c90618a53).
[2022-08-20 16:09:14] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:09:14] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:09:14] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:09:14] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:09:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 80e59f4109712ccaca5330ad67d7b316).
[2022-08-20 16:10:43] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:10:43] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:10:43] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:10:43] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:10:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9f0065e47be104c1b5924cccac12d63a).
[2022-08-20 16:44:09] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:44:09] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:44:09] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:44:09] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:44:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 92aa45425e3e2c16ca2841c86f77ab7f).
[2022-08-20 16:45:29] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:45:29] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:45:29] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:45:29] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:45:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2ab3c1b4879277e1765a463ba67bc88e).
[2022-08-20 16:47:06] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:47:06] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:47:06] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:47:06] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:47:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ab3ca62ecc125d7281a32e0cfc19db63).
[2022-08-20 16:50:27] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:50:27] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:50:27] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:50:27] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:50:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6bfd1d490630edd66fca94a7a3557882).
[2022-08-20 16:51:41] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:51:41] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:51:41] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:51:41] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:51:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bdb553b65c3ceebbf783f5e525af0a3e).
[2022-08-20 16:53:07] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:53:07] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:53:07] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:53:07] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:53:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 502bdfa7a8c0798a97da025ee2b73f77).
[2022-08-20 16:54:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:54:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:54:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:54:02] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:54:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a53d218a251b39fefc19d4c867f8a301).
[2022-08-20 16:55:05] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 16:55:05] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 16:55:05] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 16:55:05] [INFO    ] discord.client: logging in using static token
[2022-08-20 16:55:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fd110b9af49aa491af1f5536f2b8ad3d).
[2022-08-20 17:02:23] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:02:23] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:02:23] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:02:23] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:02:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9f0e6fd072a76d338e936e82ccd76789).
[2022-08-20 17:06:15] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:06:15] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:06:15] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:06:15] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:06:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bc2985cc604270512702d06eeefcfee4).
[2022-08-20 17:11:58] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:11:58] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:11:58] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:11:58] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:11:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e784f7756543bb51aefe033451c8a5e1).
[2022-08-20 17:12:41] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:12:41] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:12:41] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:12:41] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:12:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1067607939a20dd0c03eb640b6fcbd2f).
[2022-08-20 17:53:00] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:53:00] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:53:00] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:53:00] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:53:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 77a4c92e465736afd53abda483517ea9).
[2022-08-20 17:56:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 17:56:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 17:56:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 17:56:04] [INFO    ] discord.client: logging in using static token
[2022-08-20 17:56:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a98110d3dfe1024ede0148d3efb610a5).
[2022-08-20 18:03:53] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:03:53] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:03:53] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:03:53] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:03:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5bf6070904937fa2c617d24d771649c3).
[2022-08-20 18:06:57] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:06:57] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:06:57] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:06:57] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:06:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 88079d289a681e78f0dffe7ca4a7039c).
[2022-08-20 18:16:31] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:16:31] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:16:31] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:16:31] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:16:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e803ec923a861b880f4c9e4174d3fa1e).
[2022-08-20 18:18:34] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:18:34] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:18:34] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:18:34] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:18:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2e082627052a413e7ee38e590bb6955a).
[2022-08-20 18:32:48] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:32:48] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:32:48] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:32:48] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:32:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 34a4125a3bde2e8dace3ae7501a5a485).
[2022-08-20 18:49:10] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:49:10] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:49:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:49:10] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:49:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a2a0796a2a9cc6eeb1e62d2b025a15ab).
[2022-08-20 18:49:55] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:49:55] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:49:55] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:49:55] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:49:56] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d26f03e93575372c133715460beb7f0).
[2022-08-20 18:53:19] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:53:19] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:53:19] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:53:19] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:53:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 622f50682a023537b28f3caa340cf3a8).
[2022-08-20 18:54:10] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 18:54:10] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 18:54:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 18:54:10] [INFO    ] discord.client: logging in using static token
[2022-08-20 18:54:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: eb3715aa0a9c83af10b1eb73b9df3f95).
[2022-08-20 19:44:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session eb3715aa0a9c83af10b1eb73b9df3f95.
[2022-08-20 22:19:38] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-20 22:19:38] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-20 22:19:38] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-20 22:19:38] [INFO    ] discord.client: logging in using static token
[2022-08-20 22:19:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ea6c68fd6e4389e3c34ae7ea83be6a42).
[2022-08-21 00:31:30] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 00:31:30] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 00:31:30] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 00:31:30] [INFO    ] discord.client: logging in using static token
[2022-08-21 07:30:09] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 07:30:09] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 07:30:09] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 07:30:09] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:36:31] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:36:31] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:36:31] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:36:31] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:37:47] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:37:47] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:37:47] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:37:47] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:38:12] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:38:12] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:38:12] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:38:12] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:39:05] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:39:05] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:39:05] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:39:05] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:39:54] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:39:54] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:39:54] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:39:54] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:40:01] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:40:01] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:40:01] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:40:01] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:41:21] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:41:21] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:41:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:41:21] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:41:32] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:41:32] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:41:32] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:41:32] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:41:38] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:41:38] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:41:38] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:41:38] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:42:19] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:42:19] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:42:19] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:42:19] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:42:25] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:42:25] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:42:25] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:42:25] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:51:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:51:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:51:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:51:02] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:51:04] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:51:04] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:51:04] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:51:04] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:51:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8f3e44c6cb2b00d5219cad6c1f903109).
[2022-08-21 08:55:29] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-21 08:55:29] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-21 08:55:29] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-21 08:55:29] [INFO    ] discord.client: logging in using static token
[2022-08-21 08:55:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fcdbce89535ca1f9dac35a8dcd0adde1).
[2022-08-21 11:09:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 12:28:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 15:54:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 16:32:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 20:26:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 21:43:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 21:45:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-21 23:18:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-22 02:19:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session fcdbce89535ca1f9dac35a8dcd0adde1.
[2022-08-22 04:44:53] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-22 04:44:53] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-22 04:44:53] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-22 04:44:53] [INFO    ] discord.client: logging in using static token
[2022-08-22 06:33:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-22 06:33:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-22 06:33:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-22 06:33:03] [INFO    ] discord.client: logging in using static token
[2022-08-22 06:33:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5cd34d06bf22ac0d1f9a9125b99f44e8).
[2022-08-22 08:28:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5cd34d06bf22ac0d1f9a9125b99f44e8.
[2022-08-22 10:32:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5cd34d06bf22ac0d1f9a9125b99f44e8.
[2022-08-22 12:12:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5cd34d06bf22ac0d1f9a9125b99f44e8.
[2022-08-22 14:14:00] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-22 14:14:00] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-22 14:14:00] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-22 14:14:00] [INFO    ] discord.client: logging in using static token
[2022-08-22 14:24:41] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-22 14:24:41] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-22 14:24:41] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-22 14:24:41] [INFO    ] discord.client: logging in using static token
[2022-08-22 18:10:49] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-22 18:10:49] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-22 18:10:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-22 18:10:49] [INFO    ] discord.client: logging in using static token
[2022-08-22 18:10:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9beaffa38ca6153eb5c2f54e7d0a6b20).
[2022-08-22 19:52:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9beaffa38ca6153eb5c2f54e7d0a6b20.
[2022-08-22 21:09:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9beaffa38ca6153eb5c2f54e7d0a6b20.
[2022-08-23 00:03:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9beaffa38ca6153eb5c2f54e7d0a6b20.
[2022-08-23 00:34:57] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 00:34:57] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 00:34:57] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 00:34:57] [INFO    ] discord.client: logging in using static token
[2022-08-23 00:34:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bccfdad9463d276da5e199a99b7298e2).
[2022-08-23 03:32:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 03:41:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 06:35:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 08:27:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 10:59:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 11:31:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session bccfdad9463d276da5e199a99b7298e2.
[2022-08-23 14:01:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 14:01:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 14:01:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 14:01:59] [INFO    ] discord.client: logging in using static token
[2022-08-23 14:02:00] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 52ac51d820fc223eb373128b9524f184).
[2022-08-23 15:30:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 52ac51d820fc223eb373128b9524f184.
[2022-08-23 15:51:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 52ac51d820fc223eb373128b9524f184.
[2022-08-23 18:51:39] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 18:51:39] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 18:51:39] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 18:51:39] [INFO    ] discord.client: logging in using static token
[2022-08-23 18:51:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 28fbc92f915fb99aa84608250c8e62b3).
[2022-08-23 19:22:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 28fbc92f915fb99aa84608250c8e62b3.
[2022-08-23 19:54:37] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 19:54:37] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 19:54:37] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 19:54:37] [INFO    ] discord.client: logging in using static token
[2022-08-23 19:54:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c6b1ef7214b00b18444f79d0f60d0a86).
[2022-08-23 20:54:02] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 20:54:02] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 20:54:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 20:54:02] [INFO    ] discord.client: logging in using static token
[2022-08-23 20:54:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3ccca0bde25c9d5e6616ab99cbbc1959).
[2022-08-23 21:57:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 3ccca0bde25c9d5e6616ab99cbbc1959.
[2022-08-23 22:43:21] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 22:43:21] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 22:43:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 22:43:21] [INFO    ] discord.client: logging in using static token
[2022-08-23 22:43:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 278e76dc8265a8e830dfa67bcf075b1b).
[2022-08-23 22:50:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-23 22:50:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-23 22:50:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-23 22:50:59] [INFO    ] discord.client: logging in using static token
[2022-08-24 08:26:09] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-24 08:26:10] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-24 08:26:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-24 08:26:10] [INFO    ] discord.client: logging in using static token
[2022-08-24 08:26:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 22c726ddcb485004d66dcc2dd460aa9e).
[2022-08-24 08:26:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-24 08:26:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-24 08:26:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-24 08:26:40] [INFO    ] discord.client: logging in using static token
[2022-08-24 08:26:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 469e2469aeddf73d3b331b5b5c1b7d59).
[2022-08-24 11:07:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 469e2469aeddf73d3b331b5b5c1b7d59.
[2022-08-24 11:44:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 469e2469aeddf73d3b331b5b5c1b7d59.
[2022-08-24 14:06:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 469e2469aeddf73d3b331b5b5c1b7d59.
[2022-08-24 17:16:52] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-24 17:16:52] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-24 17:16:52] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-24 17:16:52] [INFO    ] discord.client: logging in using static token
[2022-08-24 17:16:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c023fc22e4df14094ee3eddf8291b23e).
[2022-08-24 17:25:59] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-24 17:25:59] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-24 17:25:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-24 17:25:59] [INFO    ] discord.client: logging in using static token
[2022-08-24 17:25:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fa548b83d096f51603ebeefd38e9769f).
[2022-08-24 17:40:56] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-24 17:40:56] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-24 17:40:56] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-24 17:40:56] [INFO    ] discord.client: logging in using static token
[2022-08-25 06:12:39] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 06:12:39] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 06:12:39] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 06:12:39] [INFO    ] discord.client: logging in using static token
[2022-08-25 06:12:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 31cab2d2379b558f2fca7da8d40abb34).
[2022-08-25 08:11:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 31cab2d2379b558f2fca7da8d40abb34.
[2022-08-25 10:05:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 31cab2d2379b558f2fca7da8d40abb34.
[2022-08-25 10:38:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 31cab2d2379b558f2fca7da8d40abb34.
[2022-08-25 11:10:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 31cab2d2379b558f2fca7da8d40abb34.
[2022-08-25 12:18:17] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 12:18:17] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 12:18:17] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 12:18:17] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:20:40] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 14:20:40] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 14:20:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 14:20:40] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:21:31] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 14:21:31] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 14:21:31] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 14:21:31] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:22:24] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 14:22:24] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 14:22:24] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 14:22:24] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:24:03] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 14:24:03] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 14:24:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 14:24:03] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:24:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4942774be51afac8d03d810346ad7cf4).
[2022-08-25 14:25:32] [DEBUG   ] discord.client: onMessage has successfully been registered as an event
[2022-08-25 14:25:32] [DEBUG   ] discord.client: on_command_error has successfully been registered as an event
[2022-08-25 14:25:32] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2022-08-25 14:25:32] [INFO    ] discord.client: logging in using static token
[2022-08-25 14:25:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 57363cfa604542cdf807d7ce7e3026fb).
